Creating wgs somatic wb
eastgenomics/eggd_generate_solid_cancer_wgs_workbook pull request #1
Opened 2024-04-22 12:58 UTC by wintun12

add initial python script

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1)

2024-04-22 12:58 UTC, pep8speaks commented
Hello @wintun12! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`create_spreadsheet.py`](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py):

> [Line 26:1](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L26): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 28:63](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L28): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 374:44](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L374): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 507:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L507): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> [Line 518:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L518): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (133 > 79 characters)
> [Line 521:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L521): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 79 characters)
> [Line 524:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L524): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (143 > 79 characters)
> [Line 527:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L527): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (163 > 79 characters)
> [Line 530:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L530): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (154 > 79 characters)
> [Line 533:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L533): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (113 > 79 characters)
> [Line 536:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L536): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 539:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L539): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (222 > 79 characters)
> [Line 542:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L542): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (135 > 79 characters)
> [Line 545:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L545): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (164 > 79 characters)
> [Line 548:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L548): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (160 > 79 characters)
> [Line 551:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L551): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (132 > 79 characters)
> [Line 554:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L554): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (133 > 79 characters)
> [Line 558:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L558): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (120 > 79 characters)
> [Line 561:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L561): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 564:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L564): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 567:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L567): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (180 > 79 characters)
> [Line 570:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L570): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (255 > 79 characters)
> [Line 573:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L573): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 79 characters)
> [Line 844:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L844): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (116 > 79 characters)
> [Line 946:16](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L946): [E713](https://duckduckgo.com/?q=pep8%20E713) test for membership should be 'not in'
> [Line 962:16](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L962): [E713](https://duckduckgo.com/?q=pep8%20E713) test for membership should be 'not in'
> [Line 978:16](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L978): [E713](https://duckduckgo.com/?q=pep8%20E713) test for membership should be 'not in'
> [Line 981:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L981): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (140 > 79 characters)
> [Line 1094:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L1094): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 79 characters)
> [Line 1162:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L1162): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 1165:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07dbeee343658e3407bfe8a4e3af4c54567ac9/create_spreadsheet.py#L1165): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 1168:80](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/cd07d [...]

2024-05-13 15:03 UTC, kjwinfield approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1)* status: 0 of 14 files reviewed, 4 unresolved discussions (waiting on @wintun12)

___
*[`create_spreadsheet.py` line 65 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-NxmAJzq2zJ_SZaR7BFy:-NxmAJzq2zJ_SZaR7BFz:bab2xpc) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/82a7e7ae8f605bc54ad871a877d09ec109bc7a34/create_spreadsheet.py#L65)):*
> ```Python
>         parser = argparse.ArgumentParser()
>         parser.add_argument(
>             "--output", "-o", required=True, help="output xlsm file name"
> ```

typo   should be xlsx
___
*[`create_spreadsheet.py` line 106 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-NxmBqpy5GHWNizB-3kP:-NxmBqpy5GHWNizB-3kQ:b8zv5vk) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/82a7e7ae8f605bc54ad871a877d09ec109bc7a34/create_spreadsheet.py#L106)):*
> ```Python
>             self.download_image(img_link, "./", f"figure_{n}")
>             if n == 2:
>                 self.crop_img("figure_2.jpg", 600, 600, 2400, 2400)
> ```

is there always a set number of figures and you only ever want to crop figure 2?
if so, you could crop figure 2 that outside this loop so there's no need to use 'n'
___
*[`create_spreadsheet.py` line 316 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-NxmBEdS7QupwHXHO0HX:-NxmBEdS7QupwHXHO0HY:bw04rke) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/82a7e7ae8f605bc54ad871a877d09ec109bc7a34/create_spreadsheet.py#L316)):*
> ```Python
> 
>         # set column widths for readability
>         cell_col_width = (
> ```

is there any reason why this is a tuple of tuples, and not a list of tuples?
___
*[`create_spreadsheet.py` line 730 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-NxmCnhx6UEXcQloZaUo:-NxmCnhx6UEXcQloZaUp:b-ro3gqt) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/82a7e7ae8f605bc54ad871a877d09ec109bc7a34/create_spreadsheet.py#L730)):*
> ```Python
>         )
> 
>         # write df into excel sheet
> ```

you can write dfs to excel like this:



_Code snippet:_
```Python
df.to_excel(self.writer, sheet_name="Germline", index=False)
```


<!-- Sent from Reviewable.io -->

2024-05-20 09:45 UTC, wintun12 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @kjwinfield)

___
*[`create_spreadsheet.py` line 65 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-NxmAJzq2zJ_SZaR7BFy:-NyKNJkJ16T_yV3oDOGo:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/82a7e7ae8f605bc54ad871a877d09ec109bc7a34/create_spreadsheet.py#L65)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

typo   should be xlsx
</blockquote></details>

Done
___
*[`create_spreadsheet.py` line 106 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-NxmBqpy5GHWNizB-3kP:-NyKNN8q8HYQ02iRJgI5:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/82a7e7ae8f605bc54ad871a877d09ec109bc7a34/create_spreadsheet.py#L106)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

is there always a set number of figures and you only ever want to crop figure 2?
if so, you could crop figure 2 that outside this loop so there's no need to use 'n'
</blockquote></details>

Done
___
*[`create_spreadsheet.py` line 316 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-NxmBEdS7QupwHXHO0HX:-NyKNPbDDoV-p8YuVYaV:b-1f9gqq) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/82a7e7ae8f605bc54ad871a877d09ec109bc7a34/create_spreadsheet.py#L316)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

is there any reason why this is a tuple of tuples, and not a list of tuples?
</blockquote></details>

Since the items don't need to be mutable, I use the tuples. 
___
*[`create_spreadsheet.py` line 730 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-NxmCnhx6UEXcQloZaUo:-NyKNXNWEoXJRPkq2lh3:bc5xy18) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/82a7e7ae8f605bc54ad871a877d09ec109bc7a34/create_spreadsheet.py#L730)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

you can write dfs to excel like this:
</blockquote></details>

I think I tried that method before. If I understand correctly, it will write the df into excel sheet starting from the 1st row, 1st column. If I want to write the df in particular rows and columns, can I still use that method? 


<!-- Sent from Reviewable.io -->

2024-05-23 12:08 UTC, kjwinfield requested changes
> Reviewed 9 of 14 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @wintun12)

___
*[`create_spreadsheet.py` line 1226 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-Ny_KIjY7oVkd6MRm9Nn:-Ny_KIjY7oVkd6MRm9No:be4fvwi) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/d7f080c8a44de38729a132bec6d7a18f6472fdf9/create_spreadsheet.py#L1226)):*
> ```Python
>                 ";", expand=True
>             )
>             df_SV["B_LOOKUP"] = np.where(
> ```

if you make the lookup a function you won't need to repeat yourself.
___
*[`create_spreadsheet.py` line 1268 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-Ny_JiN_-0ER3IYk7KgT:-Ny_JiN_-0ER3IYk7KgU:b-xentn0) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/d7f080c8a44de38729a132bec6d7a18f6472fdf9/create_spreadsheet.py#L1268)):*
> ```Python
>         df_SV["Comments"] = ""
>         # look up A_Gene in df_refgene
>         df_SV["Alteration_RefGene"] = df_SV["A_Gene"].map(
> ```

you could avoid repeating yourself by making this a function, something like:



_Code snippet:_
```Python
def look_up_a_gene(a, b):
    df[a] = df["A_Gene"].map(self.df_refgene.set_index("Gene")[b])
```


<!-- Sent from Reviewable.io -->

2024-05-23 15:44 UTC, wintun12 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @kjwinfield)

___
*[`create_spreadsheet.py` line 1226 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-Ny_KIjY7oVkd6MRm9Nn:-Nya6zVG-Ux4k87w3bW7:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/d7f080c8a44de38729a132bec6d7a18f6472fdf9/create_spreadsheet.py#L1226)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

if you make the lookup a function you won't need to repeat yourself.
</blockquote></details>

Done
___
*[`create_spreadsheet.py` line 1268 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-Ny_JiN_-0ER3IYk7KgT:-Nya705f86oI3ZWW4Cdy:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/d7f080c8a44de38729a132bec6d7a18f6472fdf9/create_spreadsheet.py#L1268)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

you could avoid repeating yourself by making this a function, something like:
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-05-24 15:14 UTC, wintun12 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @kjwinfield)

___
*[`create_spreadsheet.py` line 1226 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-Ny_KIjY7oVkd6MRm9Nn:-Nyf9jDvB4IcCCxFWIBz:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/d7f080c8a44de38729a132bec6d7a18f6472fdf9/create_spreadsheet.py#L1226)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

i think you can do the same as below here, i.e. loop over your queries, writing out the function call once
</blockquote></details>

Done
___
*[`create_spreadsheet.py` line 1268 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-Ny_JiN_-0ER3IYk7KgT:-Nyf9m3I7yKROBhIptVd:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/d7f080c8a44de38729a132bec6d7a18f6472fdf9/create_spreadsheet.py#L1268)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

you can shorten this by calling the function in a loop:
e.g.

lookup_dict = {"Origin_RefGene": "Origin", "Entities_RefGene": "Entities"}

for k, v in lookup_dict:
          df_SV[k] = self.lookup(df_SV, self.df_refgene, "A_Gene", "Gene", v)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-05-24 15:35 UTC, kjwinfield reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1)* status: 13 of 14 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-14 10:04 UTC, kjwinfield requested changes
> Reviewed 8 of 10 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1)* status: 17 of 19 files reviewed, 6 unresolved discussions (waiting on @wintun12)

___
*[`main.nf` line 9 at r7](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-KqWQp4vTtJuTtD9X7:-O-KqWQp4vTtJuTtD9X8:bsc9xd8) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/340e6dcd44910bba8eca7e4cb21fca10592b54d9/main.nf#L9)):*
> ```Nextflow
>    publishDir params.outdir, mode:'copy'
>    tag "${reads[0]}, ${reads[1]}, ${reads[2]}"
>     
> ```

there's a few instances of whitespace in the main.nf and the config which should be removed
___
*[`main.nf` line 53 at r7](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-L7XXv8Ow6GD3vHBJ5:-O-L7XXv8Ow6GD3vHBJ6:b-81rtpz) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/340e6dcd44910bba8eca7e4cb21fca10592b54d9/main.nf#L53)):*
> ```Nextflow
>   .combine(sv1_ch, by: 0)
>   .combine(html1_ch, by: 0)    
>   .map { id, v, sv,html -> [v, sv,html] }, params.hotspots, params.refgenegp, params.clinvar, params.clinvar_index)    
> ```

should there be a space between sv,html ?
___
*[`nextflow.config` line 7 at r7](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-LAde7A-UVBxxUwnUJ:-O-LAde7A-UVBxxUwnUK:b-evk0e6) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/340e6dcd44910bba8eca7e4cb21fca10592b54d9/nextflow.config#L7)):*
> ```Nextflow
> params.html_file = "*supplementary.html"
> params.hotspots = ""
> params.refgenegp = ""
> ```

feel free to ignore but i would read gp as "gene panel" so maybe this should be renamed to refgene_group as that is the file it is using, unless there is a more indicative name for the file
___
*[`nextflow_schema.json` line 2 at r7](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-LA8MB1nfdakAe6DZo:-O-LA8MB1nfdakAe6DZp:b-oroxpb) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/340e6dcd44910bba8eca7e4cb21fca10592b54d9/nextflow_schema.json#L2)):*
> ```JSON
> {
>   "description": "app/applet parameters",
> ```

maybe include app(let) name
___
*[`nextflow_schema.json` line 14 at r7](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-LAJPTAYLXMHOpdO1A:-O-LAJPTAYLXMHOpdO1B:b-bpspvs) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/340e6dcd44910bba8eca7e4cb21fca10592b54d9/nextflow_schema.json#L14)):*
> ```JSON
>             "format": "file-path",
>             "default": "project-GkG4Zf84Yj359Q9JYbbqbFpy:file-GkG4q6j4Yj36y2VXZzqB09J5"
>           },
> ```

should these be moved to 001 reference and that project named in the config?
i think from the readme the clinvar ones are already in 001_Ref so those could be used here
___
*[`README.md` line 27 at r7](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-LBbPEA2vl-hO0pH45:-O-LBbPF7w0LAX24DkfI:b9gpyeh) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/340e6dcd44910bba8eca7e4cb21fca10592b54d9/README.md#L27)):*
> ```Markdown
> -irefgenegp="project-GkG4Zf84Yj359Q9JYbbqbFpy:file-GkZk7vQ4Yj31Z7v5Bz79PV5X" \
> -iclinvar="project-Fkb6Gkj433GVVvj73J7x8KbV:file-GjP2v0j42VYfY5qfYGVKxy79" \
> -iclinvar_index="project-Fkb6Gkj433GVVvj73J7x8KbV:file-GjP2vG842VYjBz0VfGQBZ7F8" \
> ```

maybe note in the readme that these are set by default in the app so don't need to be specified each time and give info about what files are default


<!-- Sent from Reviewable.io -->

2024-06-14 12:06 UTC, wintun12 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1)* status: 13 of 19 files reviewed, 6 unresolved discussions (waiting on @kjwinfield)

___
*[`main.nf` line 9 at r7](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-KqWQp4vTtJuTtD9X7:-O-LImej0yjUGZzkqno5:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/340e6dcd44910bba8eca7e4cb21fca10592b54d9/main.nf#L9)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

there's a few instances of whitespace in the main.nf and the config which should be removed
</blockquote></details>

Done
___
*[`main.nf` line 53 at r7](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-L7XXv8Ow6GD3vHBJ5:-O-LIne77Em0K892Ci9v:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/340e6dcd44910bba8eca7e4cb21fca10592b54d9/main.nf#L53)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

should there be a space between sv,html ?
</blockquote></details>

Done
___
*[`nextflow.config` line 7 at r7](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-LAde7A-UVBxxUwnUJ:-O-LOIEc8AAkByerYMJL:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/340e6dcd44910bba8eca7e4cb21fca10592b54d9/nextflow.config#L7)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

feel free to ignore but i would read gp as "gene panel" so maybe this should be renamed to refgene_group as that is the file it is using, unless there is a more indicative name for the file
</blockquote></details>

Done
___
*[`nextflow_schema.json` line 2 at r7](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-LA8MB1nfdakAe6DZo:-O-LIr0aEvNsaWpG0jZy:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/340e6dcd44910bba8eca7e4cb21fca10592b54d9/nextflow_schema.json#L2)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

maybe include app(let) name
</blockquote></details>

Done
___
*[`nextflow_schema.json` line 14 at r7](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-LAJPTAYLXMHOpdO1A:-O-LIWwE-bHmC_9L2ZLv:bmcg29y) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/340e6dcd44910bba8eca7e4cb21fca10592b54d9/nextflow_schema.json#L14)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

should these be moved to 001 reference and that project named in the config?
i think from the readme the clinvar ones are already in 001_Ref so those could be used here
</blockquote></details>

The ref files (for hotspots and refgene_group) will be moved to 001 once signed off, but at the moment, they are not signed off yet.
___
*[`README.md` line 27 at r7](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-LBbPEA2vl-hO0pH45:-O-LHOGW7YJR10BL8u1p:b-ggd61l) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/340e6dcd44910bba8eca7e4cb21fca10592b54d9/README.md#L27)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

maybe note in the readme that these are set by default in the app so don't need to be specified each time and give info about what files are default
</blockquote></details>

I think these files still need to be defined in the command line as the default is schema file is just for info but are not callable. That's why I put the red-flag note at the end of READme file that the current dxpy version does not allow to specify fileID URI in the config/schema and only allow to in specify in the command line. I have checked with DNAnexus and they are aware of this caveat. I was told by DNAnexus that they are working on it and in the next dxpy version, fileID will be able to specify in the config so no longer need to put in the command line. As said in my Note, this is to update the nextflow app once dxpy version with that feature is released. Till then, the input files with fileID have to specify in the command line. But if we really don't want to do that, we can define them in the config file by the file path (but not the fileID). I think Matt prefer to use fileID instead of file path, that's why I use this way. To prevent the confusion, I remove all the default file path in the schema file. 
Note: specifying file ID in config file was doable in lower version of dxpy (lower than 0.36), but it's no longer available in higher version. But I need to use higher version to be able to use docker tarball


<!-- Sent from Reviewable.io -->

2024-06-14 12:12 UTC, kjwinfield requested changes
> Reviewed 1 of 10 files at r7, 3 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1)* status: 17 of 19 files reviewed, 2 unresolved discussions (waiting on @wintun12)

___
*[`main.nf` line 9 at r7](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-KqWQp4vTtJuTtD9X7:-O-Ldg4nC1P1qOQeDMLP:bxbgasy) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/340e6dcd44910bba8eca7e4cb21fca10592b54d9/main.nf#L9)):*
<details><summary><i>Previously, wintun12 wrote…</i></summary><blockquote>

Done
</blockquote></details>

Sorry the indentation is fine, the whitespace is highlighted in reviewable with red dots, and is still there in places e.g. 
![image.png](https://files.reviewableusercontent.io/images/reviewable/71272357/nZ6WEyWnHFdVAuRQP57x320b/image.png)
___
*[`README.md` line 27 at r7](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-LBbPEA2vl-hO0pH45:-O-LeBdF4ttCBb_v5-rt:b-ybey95) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/340e6dcd44910bba8eca7e4cb21fca10592b54d9/README.md#L27)):*
<details><summary><i>Previously, wintun12 wrote…</i></summary><blockquote>

I think these files still need to be defined in the command line as the default is schema file is just for info but are not callable. That's why I put the red-flag note at the end of READme file that the current dxpy version does not allow to specify fileID URI in the config/schema and only allow to in specify in the command line. I have checked with DNAnexus and they are aware of this caveat. I was told by DNAnexus that they are working on it and in the next dxpy version, fileID will be able to specify in the config so no longer need to put in the command line. As said in my Note, this is to update the nextflow app once dxpy version with that feature is released. Till then, the input files with fileID have to specify in the command line. But if we really don't want to do that, we can define them in the config file by the file path (but not the fileID). I think Matt prefer to use fileID instead of file path, that's why I use this way. To prevent the confusion, I remove all the default file path in the schema file. 
Note: specifying file ID in config file was doable in lower version of dxpy (lower than 0.36), but it's no longer available in higher version. But I need to use higher version to be able to use docker tarball
</blockquote></details>

Cool, that makes sense - once the files have been signed off then the readme can be changed to have the example paths point to 001_ref but not essential at this point


<!-- Sent from Reviewable.io -->

2024-06-14 12:13 UTC, kjwinfield reviewed
> Reviewed 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @wintun12)



<!-- Sent from Reviewable.io -->

2024-06-17 07:22 UTC, wintun12 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1)* status: 16 of 19 files reviewed, 1 unresolved discussion (waiting on @kjwinfield)

___
*[`main.nf` line 9 at r7](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-KqWQp4vTtJuTtD9X7:-O-_3hpBDYk0ogGfLwyd:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/340e6dcd44910bba8eca7e4cb21fca10592b54d9/main.nf#L9)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

Sorry the indentation is fine, the whitespace is highlighted in reviewable with red dots, and is still there in places e.g. 
![image.png](https://files.reviewableusercontent.io/images/reviewable/71272357/nZ6WEyWnHFdVAuRQP57x320b/image.png)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-06-17 12:36 UTC, kjwinfield requested changes
> Reviewed 2 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1)* status: all files reviewed, 10 unresolved discussions (waiting on @wintun12)

___
*[`bin/create_spreadsheet.py` line 75 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-_o8SD8UA5A4RT4zD2:-O-_o8SD8UA5A4RT4zD3:b-hl6krn) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L75)):*
> ```Python
>         )
>         parser.add_argument(
>             "--refgenegp", "-rgg", required=True, help="refgenegroup ref file"
> ```

could this be renamed to match the variable name i.e. refgene_group
___
*[`bin/create_spreadsheet.py` line 1095 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-aAjnF-u1dpmkFXWnU:-O-aAjnF-u1dpmkFXWnV:b-2g59vm) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L1095)):*
> ```Python
>                     "Gene",
>                     {
>                         "GRCh38 coordinates": lambda x: ",".join(x),
> ```

could you explain to me what these lambda function are doing? usually a lambda function would be defined and then reused in multiple places.
i've tried to figure it out and i'm a bit lost (sorry!)
___
*[`bin/create_spreadsheet.py` line 1356 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-aBOeV6lOspoGGMyIT:-O-aBOeV6lOspoGGMyIU:b87fmqt) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L1356)):*
> ```Python
>             inplace=True,
>         )
>         self.SNV_copy = df
> ```

could you rename to be clear that this is a copied df?
___
*[`bin/create_spreadsheet.py` line 1446 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-_x-j68EPZ45IS7tJ0:-O-_x-j68EPZ45IS7tJ1:bw4yky3) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L1446)):*
> ```Python
>         elif df_SV["fusion_count"].max() > 2:
>             print("More than 2 fusion")
>             sys.exit(1)
> ```

same as above i'd make this a runtime error + add more detail to error message (include what the fusion it is and how many)
Same question: would there never be two? have we agreed to filter out more than two?
___
*[`bin/create_spreadsheet.py` line 1461 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-_voVN484SRh-StupD:-O-_voVN484SRh-StupE:bpts8bn) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L1461)):*
> ```Python
>             lambda x: "{:,.0f}".format(x["Size"]), axis=1
>         )
>         # get gene counts and look up for each gene
> ```

this is not blocking but i think the following section repeats a lot of the same code and could be converted into a function or made more DRY somehow 
___
*[`bin/create_spreadsheet.py` line 1495 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-_vcOu3Y3G8AeK6cuI:-O-_vcOu3Y3G8AeK6cuJ:b-78ynmd) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L1495)):*
> ```Python
>         else:
>             print("SV got more than 3 genes")
>             sys.exit(1)
> ```

better to raise a runtime error here and include an error message with information for the user i.e. what SV and what genes

also: why does having more than 3 genes cause it to fail? was this agreed with Jamie?
___
*[`bin/create_spreadsheet.py` line 1508 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-_rgAwBRJLvMjlvSJp:-O-_rgAx0k5SgYgajfAd:b-mbfq1l) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L1508)):*
> ```Python
>             or col.startswith("Neuro")
>             or col.startswith("Ovary")
>             or col.startswith("Haem")
> ```

you can make this DRYer by putting all your query starting phrases in a tuple like this:



_Code snippet:_
```Python
to_lookup = ("COSMIC", "Paed", "Sarc", "Neuro", "Ovary", "Haem")
lookup_col = [col for col in df_SV if col.startswith(to_lookup)]
```
___
*[`bin/create_spreadsheet.py` line 1510 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-_yK1A0yXMBS0Rusav:-O-_yK1A0yXMBS0Rusaw:bm1o44u) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L1510)):*
> ```Python
>             or col.startswith("Haem")
>         ]
>         self.SV_copy = df_SV
> ```

could this variable renamed to make it clear it is a copy of a df e.g. self.SV_df_copy
___
*[`bin/create_spreadsheet.py` line 1613 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-_t_RjCs65mZkN9kn6:-O-_t_RjCs65mZkN9kn7:b-grhjs4) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L1613)):*
> ```Python
>         max_num_gene_gain = df_gain["gene_count"].max() + 1
>         if max_num_gene_gain > 1 or max_num_gene_loss > 1:
>             print("ERROR IN LOSS AND GAIN")
> ```

could this error explain more about what specifically causes the error so that the user can check. it might be good to include the numbers of gains/losses that caused the error in an f string
might be better to raise a RunTime error here than sys.exit
___
*[`bin/create_spreadsheet.py` line 1757 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-_sylB9ooFxkZSq5-D:-O-_sylB9ooFxkZSq5-E:b-ix8gxg) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L1757)):*
> ```Python
>         ws.add_image(img)
> 
>     def add_dropdonws_sheet(self, sheet_name, num_variant) -> None:
> ```

typo in function name should be dropdown; this is repeated for each reference to this function in the script


<!-- Sent from Reviewable.io -->

2024-06-19 07:38 UTC, wintun12 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1)* status: 18 of 19 files reviewed, 9 unresolved discussions (waiting on @kjwinfield)

___
*[`bin/create_spreadsheet.py` line 75 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-_o8SD8UA5A4RT4zD2:-O-jPEZD7D59J3rYDyES:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L75)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

could this be renamed to match the variable name i.e. refgene_group
</blockquote></details>

Done
___
*[`bin/create_spreadsheet.py` line 1095 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-aAjnF-u1dpmkFXWnU:-O-jPQkT9A37d0NbvLaj:bmo50sm) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L1095)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

could you explain to me what these lambda function are doing? usually a lambda function would be defined and then reused in multiple places.
i've tried to figure it out and i'm a bit lost (sorry!)
</blockquote></details>

it is to concatenate all rows with same gene name. Now I have refactor the script and it's more simple now.
___
*[`bin/create_spreadsheet.py` line 1356 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-aBOeV6lOspoGGMyIT:-O-jPh032DXocu-D7mjk:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L1356)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

could you rename to be clear that this is a copied df?
</blockquote></details>

Done
___
*[`bin/create_spreadsheet.py` line 1446 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-_x-j68EPZ45IS7tJ0:-O-jQ85xCg6eX8atihaH:b-ig19d6) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L1446)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

same as above i'd make this a runtime error + add more detail to error message (include what the fusion it is and how many)
Same question: would there never be two? have we agreed to filter out more than two?
</blockquote></details>

I have refactored the code after discussion with Jamie on Monday. In the updated script, this no longer exists
___
*[`bin/create_spreadsheet.py` line 1461 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-_voVN484SRh-StupD:-O-jQLrF2HRCrx2uhFTZ:b-ig19d6) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L1461)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

this is not blocking but i think the following section repeats a lot of the same code and could be converted into a function or made more DRY somehow
</blockquote></details>

I have refactored the code after discussion with Jamie on Monday. In the updated script, this no longer exists
___
*[`bin/create_spreadsheet.py` line 1495 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-_vcOu3Y3G8AeK6cuI:-O-jQPQS42ESf9nFkoEP:b-ig19d6) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L1495)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

better to raise a runtime error here and include an error message with information for the user i.e. what SV and what genes

also: why does having more than 3 genes cause it to fail? was this agreed with Jamie?
</blockquote></details>

I have refactored the code after discussion with Jamie on Monday. In the updated script, this no longer exists
___
*[`bin/create_spreadsheet.py` line 1508 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-_rgAwBRJLvMjlvSJp:-O-jQTZfBoUft6yFMq9X:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L1508)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

you can make this DRYer by putting all your query starting phrases in a tuple like this:
</blockquote></details>

Done
___
*[`bin/create_spreadsheet.py` line 1510 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-_yK1A0yXMBS0Rusav:-O-jQVOf0x27AGgxrgNG:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L1510)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

could this variable renamed to make it clear it is a copy of a df e.g. self.SV_df_copy
</blockquote></details>

Done
___
*[`bin/create_spreadsheet.py` line 1613 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-_t_RjCs65mZkN9kn6:-O-jQYD_C7f1aUkPQ-2h:b-ig19d6) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L1613)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

could this error explain more about what specifically causes the error so that the user can check. it might be good to include the numbers of gains/losses that caused the error in an f string
might be better to raise a RunTime error here than sys.exit
</blockquote></details>

I have refactored the code after discussion with Jamie on Monday. In the updated script, this no longer exists
___
*[`bin/create_spreadsheet.py` line 1757 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-_sylB9ooFxkZSq5-D:-O-jQaYU-UjD8Qeh3SMi:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L1757)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

typo in function name should be dropdown; this is repeated for each reference to this function in the script
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-06-20 11:02 UTC, kjwinfield approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-:-O-pEipB75mzN-uva6pb:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @wintun12)

___
*[`bin/create_spreadsheet.py` line 1757 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-_sylB9ooFxkZSq5-D:-O-pIkca65RQzcRyxnil:b-s6tsmh) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L1757)):*
<details><summary><i>Previously, wintun12 wrote…</i></summary><blockquote>

Done
</blockquote></details>

This typo still appears for me?


<!-- Sent from Reviewable.io -->

2024-06-20 11:24 UTC, wintun12 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @kjwinfield)

___
*[`bin/create_spreadsheet.py` line 1757 at r10](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1#-O-_sylB9ooFxkZSq5-D:-O-pO1GE0Z5d18lT6peR:bau95hy) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/blob/4e431d47b1a1c382ad4d0a8d0e7f5e943ac24c29/bin/create_spreadsheet.py#L1757)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

This typo still appears for me?
</blockquote></details>

Sorry, I miss some of them. Done now. 


<!-- Sent from Reviewable.io -->

2024-06-20 14:52 UTC, kjwinfield approved these changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_solid_cancer_workbook/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wintun12)



<!-- Sent from Reviewable.io -->

2024-06-20 14:52 UTC, merged